name: tm
channels:
  - conda-forge 
dependencies:
  - python=3.11
  - graph-tool
  - pandas
  - numba
  - tqdm
  - cvxpy
  - matplotlib
  - networkx
  - ipykernel
  - pytest
  - pip
  - pip:
    - jupyter
